### ISSUE TITLE
Custom debounce time

### ISSUE THREAD

**Issue by analytik** [elbywan/hyperactiv#13]
Hi again. I'm wondering if I could add a debounce feature. `batch: true` doesn't seem to reduce the number of calls much. I'm not 100% sure, but hopefully would find time to submit a PR in the next 2-3 weeks.

Questions:

1. Is this interesting at all?
2. Should I reuse `batch: boolean | integer` or add `debounce: integer` (time in ms) option?

**Comment by elbywan** [comment]
Hi @analytik,

> Is this interesting at all?

Yes it makes sense!

> Should I reuse batch: boolean | integer or add debounce: integer (time in ms) option?

I took the liberty of opening a [PR](https://github.com/elbywan/hyperactiv/pull/14) with this change since it is a small modification, can you have a look and tell me if it suits your needs?

**Comment by elbywan** [comment]
Released with `v0.8.2` 📦.
