### ISSUE TITLE
Ability to not fire reactive statements on property change? 

### ISSUE THREAD

**Issue by GoodMorgon** [elbywan/hyperactiv#17]
Hello!

I first want to second the guys from another post that this library is excellent! I really like the super-lightweight nature.

Is it possible to set a reactive object without firing its reactive depends ad-hoc (please see small example below)? This is useful when you for some reason need to change a reactive property but do **not** want  to update the reactively calculated value. 

Going batch-mode seems to be overkill if it happens on an ad-hoc basis.

```
myobject = observe({

    data        : null,
    test        : null

})


computed(() => {

     myobject.result = data + test

})

donotfirecomputed({myobject.data = 2}) #computed() should not be fired
```

**Comment by elbywan** [comment]
Hi @GoodMorgon,

> I first want to second the guys from another post that this library is excellent! I really like the super-lightweight nature.

Thanks a bunch! 🙇 

> Is it possible to set a reactive object without firing its reactive depends ad-hoc

Yes, it should be possible to do that **if** you keep a reference to the original object:

```js
const object = { data: 0 }
const observed = observe(object)
computed(() => {
  observed.result = observed.data
})

object.data = 1
console.log(observed.result) // 0
observed.data = 2
console.log(observed.result) // 2
```

**Comment by GoodMorgon** [comment]
Thank for the quick reply! 

Is this possible with the observe(object) also having properties?

Thanks
