### ISSUE TITLE
Incremental computation

### ISSUE THREAD

**Issue by hpx7** [elbywan/hyperactiv#18]
I have a use case that looks something like this:
```
const observed = observe({
    a: 1,
    b: 2,
    c: 0
})

computed(() => {
    const obj = {
        x: fn1(observed.a),
        y: fn2(observed.b),
        z: fn3(observed.c)
    }
    console.log(obj)
})

observed.a = 2 // should only rerun `fn1`
```

Assuming `fn1`, `fn2`, and `fn3` are expensive, I'd like some way to compute my object _incrementally_, meaning only recompute the values whose inputs have changed and patch the result with the previous version (which is cached).

This type of functionality may be out of scope for this library, but I wanted to check if you had any thoughts/suggestions on how to achieve this.

**Comment by hpx7** [comment]
Maybe the approach would be to define multiple `computed` functions and have a higher layer patch things together

```
const obj = {}
computed(() => {
    obj.x = fn1(observed.a)
    console.log(obj)
})
computed(() => {
    obj.y = fn1(observed.b)
    console.log(obj)
})
computed(() => {
    obj.z = fn1(observed.c)
    console.log(obj)
})
```

**Comment by elbywan** [comment]
Hi @hpx7,

> This type of functionality may be out of scope for this library, but I wanted to check if you had any thoughts/suggestions on how to achieve this.

I think that using memoization could do the trick.

```js
/// Will re-run the function only when the argument changes.
// For the sake of the example we assume that the function accepts a single argument.
const memoize = f => {
  let arg = null
  return newArg => {
    if (arg == newArg) {
      return arg
    }
    arg = newArg
    return f(newArg)
  }
}
```

And then when applied to the example you used:

```js
const [fn1, fn2, fn3] = ["fn1", "fn2", "fn3"].map(f =>
  memoize(v => {
    console.log(f)
    return v
  })
)

const observed = observe({
  a: 1,
  b: 2,
  c: 0
})

computed(() => {
  const obj = {
    x: fn1(observed.a),
    y: fn2(observed.b),
    z: fn3(observed.c)
  }
  console.log(obj)
})

// Prints:

/*
"fn1"
"fn2"
"fn3"
Object {x: 1, y: 2, z: 0}
*/

observed.a = 2 

// Prints:

/*
"fn1"
Object {x: 2, y: 2, z: 0}
*/
```

**Comment by hpx7** [comment]
That looks like a good pattern, thanks @elbywan!
