### ISSUE TITLE
TypeScript declaration

### ISSUE THREAD

**Issue by privatenumber** [elbywan/hyperactiv#21]
Thank you for this package!

Would like to see TypeScript declaration and ESM distribution if possible.

**Comment by elbywan** [comment]
Hey @privatenumber,

> Thank you for this package!

❤️ 

> Would like to see TypeScript declaration and ESM distribution if possible.

I would love to write some type definitions, but I'm unfortunately not as available as I used to be. 
But as soon as a have some time to dedicate I'll definitely consider working on this 👍 .

Regarding the ESM distrib, the hyperactiv package contains its own sourcecode mapped to the package.json module field (`"module": "src/index.js"`) so it should be good to go. Did you have anything else in mind? (node `exports` maybe?)

**Comment by elbywan** [comment]
Allright so I just pushed a commit adding nodejs `exports` and typings for the core module (as well as partial ts bindings for the rest).

**Comment by privatenumber** [comment]
Thanks for the fast implementation @elbywan ! 🙏
