### ISSUE TITLE
UMD require not working

### ISSUE THREAD

**Issue by eldoy** [elbywan/hyperactiv#23]
Thanks for this lib, but I'm getting an error when trying to use `require`:

```js
const hyperactiv = require('hyperactiv')
```

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`

Is it no longer UMD like stated in README?

**Comment by elbywan** [comment]
Hey @eldoy,

> Is it no longer UMD like stated in README?

Thanks for reporting the issue!

Hyperactiv is still bundled as an UMD package, but the problem comes from the package.json file `type` field which wrongly declares hyperactiv as an ES module.

I have published `v0.10.2` that should fix it hopefully.

**Comment by eldoy** [comment]
Yup, that fixes it! Thanks!
