### ISSUE TITLE
benchmark?

### ISSUE THREAD

**Issue by hyusetiawan** [elbywan/hyperactiv#24]
I wonder if there is a benchmark comparing hyperactive to the other solutions for reactive data structures? most notably mobx

**Comment by elbywan** [comment]
Hey @hyusetiawan thanks for raising the issue 👋 

I found a benchmark from [maverickjs](https://github.com/maverick-js/observables/tree/main/bench), adapted from [cellx](https://github.com/Riim/cellx/tree/master/perf).

I tried to adapt it and to add the mobx implementation but as I am not familiar with its API I may have used it incorrectly.

You can check the code here: https://github.com/elbywan/hyperactiv/tree/master/bench

Nevertheless here are the raw results:

<img width="1225" alt="Capture d’écran 2022-08-29 à 00 47 20" src="https://user-images.githubusercontent.com/3428394/187097699-516dfca4-b7ca-4813-bf31-e53510ee41df.png">
:

**Comment by hyusetiawan** [comment]
this is a great start! It looks like, if I read the benchmark correctly, hyperactiv though not the fastest, it still has a very respectable performance with a very low API surface. This could be good marketing content as part of the github page? I know I'd be convinced :D

**Comment by elbywan** [comment]
> This could be good marketing content as part of the github page? I know I'd be convinced :D

@hyusetiawan Haha true, I'll find something to add there 👍

**Comment by elbywan** [comment]
I just added a section about performance in the readme, so I think this issue can be closed now.
