### ISSUE TITLE
[bug] observing date changes `this`

### ISSUE THREAD

**Issue by hyusetiawan** [elbywan/hyperactiv#30]
calling observe on a date object, makes all operations throw: `TypeError: this is not a Date object.`

to reproduce:
```
const test = observe({
      date: new Date(),
    })
test.date.getDate()
```

**Comment by elbywan** [comment]
Only POJOs and arrays are observables, for builtin classes there is no guarantee. 

Date instances should be ignored using the `{ ignore: … }` [option](https://github.com/elbywan/hyperactiv#observe).
